# Generated by Django 5.1.2 on 2024-10-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statements',
            name='id',
        ),
        migrations.AlterField(
            model_name='statements',
            name='psid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
