# Generated by Django 5.1.2 on 2024-10-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_statements_id_alter_statements_psid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statements',
            name='psid',
        ),
        migrations.AddField(
            model_name='statements',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
