# Generated by Django 5.1.2 on 2024-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_statements_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('time', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=50)),
                ('maxsub', models.IntegerField(default=200)),
                ('statustext', models.CharField(max_length=75)),
                ('isClosed', models.BooleanField(default=False)),
            ],
        ),
    ]
