# Generated by Django 5.1.2 on 2024-10-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='bgcolor',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='redirectURI',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
    ]
