# Generated by Django 5.1.2 on 2024-10-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_events_bgcolor_events_redirecturi'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='imageurl',
            field=models.CharField(default='abc', max_length=25),
            preserve_default=False,
        ),
    ]
