# Generated by Django 5.1.2 on 2024-10-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_events_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=100)),
                ('mem1', models.CharField(max_length=100)),
                ('roll1', models.CharField(max_length=100)),
                ('mem2', models.CharField(max_length=100)),
                ('roll2', models.CharField(max_length=100)),
                ('mem3', models.CharField(max_length=100)),
                ('roll3', models.CharField(max_length=100)),
                ('mem4', models.CharField(max_length=100)),
                ('roll4', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.events')),
            ],
        ),
    ]
