# Generated by Django 5.1.2 on 2024-10-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_registrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrations',
            options={'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterField(
            model_name='registrations',
            name='mem1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='mem2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='mem3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='mem4',
            field=models.CharField(max_length=200),
        ),
    ]
