# Generated by Django 5.1.2 on 2024-10-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_registrations_options_alter_registrations_mem1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='contact',
            field=models.CharField(default='8838492241', max_length=20),
            preserve_default=False,
        ),
    ]
