# Generated by Django 5.1.2 on 2024-10-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_hackathonreg_ch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hackathonreg',
        ),
    ]
