# Generated by Django 5.1.2 on 2024-10-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_hackathonreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='submitted',
            field=models.IntegerField(default=0),
        ),
    ]
