name: Deploy Smartathon-24

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no phariprasath2006@34.131.154.92 << 'EOF'
            cd /opt/smartathon
            git fetch origin main
            git reset --hard origin/main
            source venv/bin/activate

            # Install/update dependencies
            pip install -r requirements.txt

            # Run collectstatic
            python manage.py collectstatic --noinput

            # Run migrations
            python manage.py migrate

            # Run tests before restarting (optional but recommended)
            python manage.py test

            # Restart services
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF
